### ISSUE TITLE
[Upstream Issue] Error text shown above and in top bar; top and bottom bars transparent

### ISSUE THREAD

**Issue by paanvaannd** [blahsd/supernerd.widget#23] opened 2018-05-05 19:08 UTC
I am assuming that #21 was referencing this problem as well though it was not expanded upon. I have posted a screenshot for clarity:

<img width="2560" alt="error" src="https://user-images.githubusercontent.com/16567134/39666580-cc3f9218-5073-11e8-9fa0-ff93ddf532b0.png">

~~Interestingly, for some reason, the bottom bar does not show up in the screenshot. It looks similar to the top bar except that there is no error text and only a power off symbol shown in the center with nothing else.~~ The picture was cropped when I was looking at it; the bottom bar does show up in the image above.

I installed Übersicht through its desktop installer (I can't find the Homebrew package...) disabled my desktop using the provided command, and installed supernerd through cloning the repository to the Übersicht widgets folder as outlined in the README. Other widgets are working properly, so this doesn't seem to be an installation method issue or one with Übersicht itself, I believe. I have disabled all other Übersicht packages for the moment for troubleshooting and that has not helped.

I use Little Snitch for network monitoring. I tried to disable this to ensure it wasn't breaking any connections which caused downstream errors in supernerd. After disabling network monitoring and both restarting and refreshing Übersicht, the error persisted.

The animations are functional (mousing over the volume icon reveals volume percentage, etc.) but are likely not properly styled.

No modifications were made to the provided scripts. I am not certain whether the error text visible in the interface contains the entire error or only part of it (probably the latter).

Assistance would be much appreciated!

**Comment by blahsd** [comment] 2018-05-05 19:24
Hey thanks for reaching out. Could you get me the full path of the directory in which you installed the widget and a full tree of the files within? If you don't have any comparable utility, you could use `tree` command ([installation instructions](https://rschu.me/list-a-directory-with-tree-command-on-mac-os-x-3b2d4c4a4827)).

Also, it seems that I had omitted a passage in the installation in order to do it through brew – you need to tap a cask that most users would have used already probably, so that's why it didn't come up before, but naturally not all. If you could help me out by uninstalling Ubersicht and reinstalling it through brew with the new instructions in the readme, that would help me enormously to understand if we sorted out the problem.

**Comment by paanvaannd** [comment] 2018-05-05 20:34
Thank you for the quick response!

I had used the `brew install ubersicht` command instead of `brew cask install ubersicht` before, which is why I could not find the package. I uninstalled the old Übersicht package installed from the desktop installer through CleanMyMac to (hopefully) get rid of any configuration files as well and have reinstalled Übersicht through the `brew cask install ubersicht` command.

I then checked the Übersicht widgets folder (default location at `$HOME/Application\ Support/Übersicht/widgets`) and confirmed that it was empty. I issued the provided `git clone` command from the README to clone the repository to this directory. Here is a screenshot of the `git clone` command and `tree` on the Übersicht directory:

<img width="1250" alt="untitled" src="https://user-images.githubusercontent.com/16567134/39667343-b8c27c06-5081-11e8-9a81-5906184eb737.png">

(note: username redacted, but the path is simply the expansion of $HOME)

Even after all of this, the errors persist, unfortunately. However, there now seems to be overlapping text at the very top-left corner of the screen instead:

<img width="2054" alt="untitled2" src="https://user-images.githubusercontent.com/16567134/39667356-deb1171a-5081-11e8-8e7a-a00436e260ff.png">

(note: the bottom bar remains the same as in the initial screenshot post so I have only posted the relevant top portion of the screen)

OS & app versions:
* macOS 10.13.4
* Übersicht Version 1.2

I notice in the error at the top-left of the top bar that it mentions: `chunkc: connection failed!` Is chunkwm required to run this widget? I have it installed (also through homebrew) but disabled it until I could work out some conflicting keyboard shortcuts.

P.S. Your last README commit seems to have creates a huge code chunk object of all text after your modified `brew cask install ubersicht` command! Just wanted to point that out here instead of bothering you with another issue :+)

**Comment by blahsd** [comment] 2018-05-05 23:04
> Thank you for the quick response!
No worries. I live for this shit actually.

Ok so thanks for getting that tree, it definitely rules out a bunch of possible issues with the file positioning. So this brings us to something you mentioned...

> I notice in the error at the top-left of the top bar that it mentions: chunkc: connection failed! Is chunkwm required to run this widget? I have it installed (also through homebrew) but disabled it until I could work out some conflicting keyboard shortcuts.

Yes! That's where it gets the focused desktop information. And I'm going to go ahead and assume that all of the other errors might just be referencing scripts you are not running. So, for instance, it seems that you are running the widget that controls mpd through mcp – if you are not running either, that could be the cause of the error. So to sum up:

* chunkwm is required to get the focused desktop indication
* mpd and mcp are required to get the music indicator. If you don't use mpc/mcp you should disable apps-and-music.coffee (for instance by renaming it to apps-and-music.coffee.optional) and enable apps-and-itunes.coffee.optional (by renaming it to apps-and-itunes.coffee).

With regards to the disappearing bars, the issue seems to be that you are not using wal, but your css-loader.coffee is looking for wal's output to gather colors from it. If you don't want to use wal, you should open up css-loader.coffee and change this line:

`    @import url(supernerd.widget/styles/colors-wal.css);`

to this:

`    @import url(supernerd.widget/styles/colors.css); `

Then you can edit the colors by editing colors.css.

Let me know if it works!

> P.S. Your last README commit seems to have creates a huge code chunk object of all text after your modified brew cask install ubersicht command! Just wanted to point that out here instead of bothering you with another issue :+)

Ah fuck yeah thanks, I'm gonna fix that right away

Honestly if you weren't using all of these utilities in the first place, how the fuck would you have known that you needed them? I've now updated the readme so it's clearer, next step will be providing useful error messages instead of the incomprehensible shit you were getting.

**Comment by paanvaannd** [comment] 2018-05-05 23:40
Okay, that's really helpful information!

I disabled apps-and-music.coffee, enabled apps-and-itunes.coffee, made the suggested changes to css-loader.coffee, and started skhd and chunkwm.

Colors work now, yay! I'll get around to tinkering with wal later but it's good to know it works without it.

There seems to be some build error with apps-and-itunes.coffee. No modifications were made to this file other than removing the trailing ".optional" portion of the original name to activate the module. While the module is active, a text error persists in the top-left corner as pictured in the previous screenshots but with some nondescript error (but here's a picture, just in case):

<img width="988" alt="untitled3" src="https://user-images.githubusercontent.com/16567134/39668395-af1aac3c-509a-11e8-85d0-23a2b4df1378.png">

Disabling apps-and-itunes.coffee results in that error text disappearing. Even while the above error is showing, playing a song in iTunes results in unformatted plain text displayed after the error message as [artist name] - [track name].

Similarly, enabling time-date.coffee gives the following error, while disabling it results in that error disappearing from the top-left of the screen:

<img width="386" alt="untitled4" src="https://user-images.githubusercontent.com/16567134/39668424-6d9db33e-509b-11e8-8bf3-2a94d646e2a5.png">

**Comment by blahsd** [comment] 2018-05-06 12:45
Ok, so, mixed response here. 

- **time-date.coffee:** I'll have to do a mea culpa here. I did not maintain this at all because I maybe maybe might have completely forgotten that this widget existed at all. I'm actually going to remove it because it makes no sense to have it in given how everything else is set up, until I can actually work out a more modular system that let's users mix and match every indicator exactly how they want to. I recommend you use date-weather.coffee instead.

- **apps-and-itunes.coffee:** Weird, because my apps-and-itunes works fine. So now I'm wondering if it might depend on whether you have or not all of the apps installed. Do you **not** have Spotify installed? If that's the culprit I will have to split it in two separate widgets, one for iTunes, one for Spotify...

**Comment by paanvaannd** [comment] 2018-05-06 15:21
I can live without the time-date.coffee widget, no problem :+)

I did not have Spotify installed at that time. Upon installation and setup of Spotify, everything is working as it should be! That does seem to be the issue here so splitting the iTunes and Spotify modules may help or even wrapping things up in a `try/catch` or `if/else` block?

**Comment by blahsd** [comment] 2018-05-08 06:58
I think there might be an issue upstream here – I don't know how to handle errors because it seems like the ubersicht code shits itself before the issue can be handled by my code. 

So I was messing around with different frameworks, and I got a bit carried away so I [remade the entire bar as a standalone app](https://www.github.com/blahsd/snwe). This handles error extremely well. If you have the time I'd love for you to check it out, I'm now evaluating if I should consider switching development altogether.

**Comment by blahsd** [comment] 2018-05-25 16:24
Closing because it's not really up to the widget

**Closed as completed by blahsd** 2018-05-25 16:24 UTC
